-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQghzu2u4ll6klHhFiV
S+FkvHPG+KaA8VAXJBVwuewV1/CgCgYIKoZIzj0DAQehRANCAASd7RTanHFN68OL
m+n24Is//gycTcVlXnCJfaouOQpzlvvNwaYhSs2X8EE1gCv75cv1sf1UWFUEgeCv
wtBoRc1O
-----END PRIVATE KEY-----