// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgSpcksUq7WH8Fz9B6YnJhRUCEPs9I6wg',
    appId: '1:186811544956:web:ac13aac3b93c54346820f9',
    messagingSenderId: '186811544956',
    projectId: 'spacefans-shop-b2b36',
    authDomain: 'spacefans-shop-b2b36.firebaseapp.com',
    storageBucket: 'spacefans-shop-b2b36.appspot.com',
    measurementId: 'G-LF6Q84SE3M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGXgdSIPAuAr1_mh1b7IFD-Nz3qGXihPc',
    appId: '1:186811544956:android:08b414cd32336f756820f9',
    messagingSenderId: '186811544956',
    projectId: 'spacefans-shop-b2b36',
    storageBucket: 'spacefans-shop-b2b36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxwQQoadgTkI1IMtfEsT1VnADrCjb4jgk',
    appId: '1:186811544956:ios:fb475db851cac9f06820f9',
    messagingSenderId: '186811544956',
    projectId: 'spacefans-shop-b2b36',
    storageBucket: 'spacefans-shop-b2b36.appspot.com',
    iosBundleId: 'spacefans.salon.user',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxwQQoadgTkI1IMtfEsT1VnADrCjb4jgk',
    appId: '1:186811544956:ios:6d799d144e02f55e6820f9',
    messagingSenderId: '186811544956',
    projectId: 'spacefans-shop-b2b36',
    storageBucket: 'spacefans-shop-b2b36.appspot.com',
    iosBundleId: 'com.example.salonUser.RunnerTests',
  );
}
