// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgSpcksUq7WH8Fz9B6YnJhRUCEPs9I6wg',
    appId: '1:277575211611:android:848352599a09e63c5ffd7e',
    messagingSenderId: '277575211611',
    projectId: 'eliteartist-9d2a4',
    authDomain: 'spacefans-shop-b2b36.firebaseapp.com',
    storageBucket: 'eliteartist-9d2a4.appspot.com',
    measurementId: 'G-LF6Q84SE3M',
  );


  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQSuNyp9oN_3si0fbS9_scyunzKfPhNzI',  // from google-services.json
    appId: '1:277575211611:android:848352599a09e63c5ffd7e',  // from google-services.json
    messagingSenderId: '277575211611',  // from project_number
    projectId: 'eliteartist-9d2a4',  // from project_id
    storageBucket: 'eliteartist-9d2a4.appspot.com',  // from storage_bucket
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASPa5ttqH4XjRGXbZJPj604W7aYfsKA5I',  // From API_KEY in plist
    appId: '1:277575211611:ios:f6fd594eade51bf95ffd7e',  // From GOOGLE_APP_ID in plist
    messagingSenderId: '277575211611',  // From GCM_SENDER_ID in plist
    projectId: 'eliteartist-9d2a4',  // From PROJECT_ID in plist
    storageBucket: 'eliteartist-9d2a4.appspot.com',  // From STORAGE_BUCKET in plist
    iosBundleId: 'cloudtengroup.SundaySouLounge-App',  // From BUNDLE_ID in plist
  );


  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASPa5ttqH4XjRGXbZJPj604W7aYfsKA5I',
    appId: '1:277575211611:ios:f6fd594eade51bf95ffd7e',
    messagingSenderId: '277575211611',
    projectId: 'eliteartist-9d2a4',
    storageBucket: 'eliteartist-9d2a4.appspot.com',
    iosBundleId: 'cloudtengroup.SundaySouLounge-App',
  );
}
